# Generated by Django 6.0.5 on 2026-05-29 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_id",
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_name",
        ),
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="id",
            field=models.SlugField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="SavedRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.room"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
