# Generated by Django 6.0.5 on 2026-05-31 21:17

import django.db.models.deletion
from django.db import migrations, models

PLACEHOLDER_ROOM_ID = "legacy"


def parent_orphan_messages(apps, schema_editor):
    """Attach pre-existing (room-less) messages to a placeholder room.

    Messages created before rooms existed have no room. Rather than drop the FK's
    integrity or delete history, park them in a single placeholder room owned by one of
    their senders so the column can become non-null.
    """
    Message = apps.get_model("chat", "Message")
    Room = apps.get_model("chat", "Room")

    orphans = Message.objects.filter(room__isnull=True)
    owner_id = orphans.values_list("sender_id", flat=True).first()
    if owner_id is None:
        return  # no orphan messages, nothing to park

    room, _ = Room.objects.get_or_create(
        id=PLACEHOLDER_ROOM_ID,
        defaults={"owner_id": owner_id, "name": "Legacy messages"},
    )
    orphans.update(room=room)


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_room_room_id_remove_room_room_name_room_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.room",
            ),
        ),
        migrations.RunPython(parent_orphan_messages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.room",
            ),
        ),
    ]
