# Generated by Django 6.0.5 on 2026-05-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_message_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="display_name",
            field=models.CharField(default="Anonymous", max_length=255),
            preserve_default=False,
        ),
    ]
