# Generated by Django 6.0.5 on 2026-06-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_roomjoinrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="kind",
            field=models.CharField(
                choices=[("chat", "Chat"), ("join", "Join")],
                default="chat",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
